//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Versit.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Versit.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm repeat cannot be less than 0.
        /// </summary>
        public static string Exception_AlarmRepeatOutOfRange {
            get {
                return ResourceManager.GetString("Exception_AlarmRepeatOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse &quot;{0}&quot; into a VProperty&lt;{1}&gt;.
        /// </summary>
        public static string Exception_CannotParseProperty {
            get {
                return ResourceManager.GetString("Exception_CannotParseProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy property value - the types of the source and destination property are different.
        /// </summary>
        public static string Exception_CopyPropertyTypeMismatch {
            get {
                return ResourceManager.GetString("Exception_CopyPropertyTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field collection is null; you should call VBase.Initialise() first.
        /// </summary>
        public static string Exception_FieldCollectionIsNull {
            get {
                return ResourceManager.GetString("Exception_FieldCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of this field does not match the given value type.
        /// </summary>
        public static string Exception_FieldTypeMismatch {
            get {
                return ResourceManager.GetString("Exception_FieldTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of this field does not match T: {0}.
        /// </summary>
        public static string Exception_FieldTypeMismatchWith {
            get {
                return ResourceManager.GetString("Exception_FieldTypeMismatchWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of Fields cannot be null.
        /// </summary>
        public static string Exception_FieldValueCannotBeNull {
            get {
                return ResourceManager.GetString("Exception_FieldValueCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input string was in an incorrect format.
        /// </summary>
        public static string Exception_InputStringFormat {
            get {
                return ResourceManager.GetString("Exception_InputStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialise a VCalendarBase class using any ObjectType except VEVENT, VTOTO or VJOURNAL.
        /// </summary>
        public static string Exception_InvalidCalendarType {
            get {
                return ResourceManager.GetString("Exception_InvalidCalendarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name parameter cannot be null on a VProperty.
        /// </summary>
        public static string Exception_NullPropertyName {
            get {
                return ResourceManager.GetString("Exception_NullPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter collection is null!.
        /// </summary>
        public static string Exception_ParameterCollectionIsNull {
            get {
                return ResourceManager.GetString("Exception_ParameterCollectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentages must be a decimal between 0 and 1.
        /// </summary>
        public static string Exception_PercentageOutOfRange {
            get {
                return ResourceManager.GetString("Exception_PercentageOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T must be an Enum.
        /// </summary>
        public static string Exception_TypeIsNotEnum {
            get {
                return ResourceManager.GetString("Exception_TypeIsNotEnum", resourceCulture);
            }
        }
    }
}
